// <auto-generated />
using System;
using BudgetyTzar.Api.Persistence.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetyTzar.Api.Persistence.PostgreSql.Migrations
{
    [DbContext(typeof(BudgetyTzarDbContext))]
    [Migration("20260713073635_InitialPostgreSqlSchema")]
    partial class InitialPostgreSqlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("budgetytzar")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.HasSequence<long>("budget_created_order", "budgetytzar");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.ApplicationUserRecord", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<string>("UserKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_key");

                    b.HasKey("ApplicationUserId")
                        .HasName("pk_application_users");

                    b.HasIndex("UserKey")
                        .IsUnique()
                        .HasDatabaseName("ux_application_users_user_key");

                    b.ToTable("application_users", "budgetytzar", t =>
                        {
                            t.HasCheckConstraint("ck_application_users_user_key_not_blank", "length(btrim(user_key)) > 0");
                        });
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.BudgetItemRecord", b =>
                {
                    b.Property<Guid>("BudgetItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("budget_item_id");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<int>("CreatedOrder")
                        .HasColumnType("integer")
                        .HasColumnName("created_order");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("planned_amount");

                    b.HasKey("BudgetItemId")
                        .HasName("pk_budget_items");

                    b.HasAlternateKey("BudgetItemId", "ApplicationUserId", "Currency")
                        .HasName("ak_budget_items_id_owner_currency");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_budget_items_application_user_id");

                    b.HasIndex("BudgetId")
                        .HasDatabaseName("ix_budget_items_budget_id");

                    b.HasIndex("BudgetId", "CreatedOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_budget_items_budget_id_created_order");

                    b.HasIndex("BudgetId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_budget_items_budget_id_name");

                    b.HasIndex("BudgetId", "ApplicationUserId", "Currency")
                        .HasDatabaseName("ix_budget_items_budget_owner_currency");

                    b.ToTable("budget_items", "budgetytzar", t =>
                        {
                            t.HasCheckConstraint("ck_budget_items_created_order_non_negative", "created_order >= 0");

                            t.HasCheckConstraint("ck_budget_items_currency_format", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_budget_items_kind", "kind in ('Funding', 'Consumption')");

                            t.HasCheckConstraint("ck_budget_items_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_budget_items_planned_amount_range", "planned_amount > 0.00 and planned_amount <= 99999999.99");
                        });
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.BudgetRecord", b =>
                {
                    b.Property<Guid>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<long>("CreatedOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('budgetytzar.budget_created_order')")
                        .HasColumnName("created_order");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("BudgetId")
                        .HasName("pk_budgets");

                    b.HasAlternateKey("BudgetId", "ApplicationUserId")
                        .HasName("ak_budgets_id_owner");

                    b.HasAlternateKey("BudgetId", "ApplicationUserId", "Currency")
                        .HasName("ak_budgets_id_owner_currency");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_budgets_application_user_id");

                    b.HasIndex("CreatedOrder")
                        .HasDatabaseName("ix_budgets_created_order");

                    b.HasIndex("ApplicationUserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_budgets_application_user_id_name");

                    b.ToTable("budgets", "budgetytzar", t =>
                        {
                            t.HasCheckConstraint("ck_budgets_currency_format", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_budgets_created_order_non_negative", "created_order >= 0");

                            t.HasCheckConstraint("ck_budgets_name_not_blank", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_budgets_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.TransactionAllocationRecord", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<Guid>("BudgetItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_item_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.HasKey("TransactionId")
                        .HasName("pk_transaction_allocations");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_transaction_allocations_application_user_id");

                    b.HasIndex("BudgetItemId")
                        .HasDatabaseName("ix_transaction_allocations_budget_item_id");

                    b.HasIndex("BudgetItemId", "ApplicationUserId", "Currency")
                        .HasDatabaseName("ix_allocations_budget_item_owner_currency");

                    b.HasIndex("TransactionId", "ApplicationUserId", "Currency")
                        .IsUnique()
                        .HasDatabaseName("ux_allocations_transaction_owner_currency");

                    b.ToTable("transaction_allocations", "budgetytzar", t =>
                        {
                            t.HasCheckConstraint("ck_transaction_allocations_currency_format", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.TransactionRecord", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("character(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("RecordedOrder")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_order");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type");

                    b.HasKey("TransactionId")
                        .HasName("pk_transactions");

                    b.HasAlternateKey("TransactionId", "ApplicationUserId", "Currency")
                        .HasName("ak_transactions_id_owner_currency");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("ix_transactions_application_user_id");

                    b.HasIndex("ApplicationUserId", "RecordedOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_transactions_application_user_id_recorded_order");

                    b.HasIndex("ApplicationUserId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_application_user_id_transaction_date");

                    b.ToTable("transactions", "budgetytzar", t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_range", "amount > 0.00 and amount <= 99999999.99");

                            t.HasCheckConstraint("ck_transactions_currency_format", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_transactions_description_not_blank", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_transactions_recorded_order_non_negative", "recorded_order >= 0");

                            t.HasCheckConstraint("ck_transactions_type", "type in ('Credit', 'Debit')");
                        });
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.BudgetItemRecord", b =>
                {
                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.ApplicationUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_items_owner");

                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.BudgetRecord", null)
                        .WithMany()
                        .HasForeignKey("BudgetId", "ApplicationUserId", "Currency")
                        .HasPrincipalKey("BudgetId", "ApplicationUserId", "Currency")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budget_items_budget_owner_currency");
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.BudgetRecord", b =>
                {
                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.ApplicationUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_application_users_application_user_id");
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.TransactionAllocationRecord", b =>
                {
                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.ApplicationUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_owner");

                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.BudgetItemRecord", null)
                        .WithMany()
                        .HasForeignKey("BudgetItemId", "ApplicationUserId", "Currency")
                        .HasPrincipalKey("BudgetItemId", "ApplicationUserId", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_budget_item_owner_currency");

                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.TransactionRecord", null)
                        .WithOne()
                        .HasForeignKey("BudgetyTzar.Api.Persistence.PostgreSql.TransactionAllocationRecord", "TransactionId", "ApplicationUserId", "Currency")
                        .HasPrincipalKey("BudgetyTzar.Api.Persistence.PostgreSql.TransactionRecord", "TransactionId", "ApplicationUserId", "Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allocations_transaction_owner_currency");
                });

            modelBuilder.Entity("BudgetyTzar.Api.Persistence.PostgreSql.TransactionRecord", b =>
                {
                    b.HasOne("BudgetyTzar.Api.Persistence.PostgreSql.ApplicationUserRecord", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_application_users_application_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
