name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dotnet-test:
    name: dotnet-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore BudgetyTzar.sln

      - name: Test
        run: dotnet test BudgetyTzar.sln --configuration Release --no-restore
